data:
  datadir: null
  datafile: Chewie_CO_CS_2016-10-14
gpu_id: 0
logging:
  log_epochs: null
  log_interval: null
  log_model: false
neurons:
  g1: 1.2
  gin: 0.1
  gout: 0.1
  n1: 1000
  noise: 0.0
  p_recurrent: 1.0
  tau: 0.05
outdir: null
regularization:
  alpha1: 0.001
  beta1: 0.5
  clipgrad: 0.2
  delta1: 0.5 # decorrelation factor 
  gamma1: 0.001
  penalize_corr: true
seed: 20
simulation:
  sim_number: null
timestamp: null
training:
  optimizer: Adam
  batch_size: 64
  lr: 0.001
  training_trials: 2500
